#!/usr/bin/env bash
# This Bash script queries DNS information for specified subdomains of a given domain.
# It provides details about the type of DNS record and the corresponding IP address.
# Subdomains include: www, lb-01, web-01, web-02.
#
# Usage:
#   - To query all subdomains: ./script.sh <domain>
#   - To query a specific subdomain: ./script.sh <domain> <subdomain>

subdomains_all=( "www" "lb-01" "web-01" "web-02" )

runDig () {
    subdomain=$1
    domain=$2

    dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$subdomain" 'BEGIN { FS = " " } ; { print "The subdomain " s " is a " $4 " record and points to " $5 }'
}

if [ $# -eq 1 ]; then
    domain="$1"
    for i in "${subdomains_all[@]}"
    do
	runDig "$i" "$domain"
    done
elif [ $# -eq 2 ]; then
    domain="$1"
    subdomain="$2"
    runDig "$subdomain" "$domain"
fi
