#!/usr/bin/env bash
# This Bash script sets up a basic Nginx web server on an Ubuntu machine.


apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html/
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
	listen 80;
	listen [::]:80 default_server;
	root /etc/nginx/html;
	index index.html index.htm;
	location /redirect_me {
		return 301 http://cuberule.com/;
	}
}" > /etc/nginx/sites-available/default

service nginx restart
