#!/usr/bin/env bash
# Script: HAProxy Installation and Configuration
# Description: Installs HAProxy and configures it for load balancing between two web servers.
# Install software-properties-common for managing repositories.
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 87235-web-01 54.90.49.208:80 check\n\tserver 87235-web-02 100.26.226.119:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
