#!/usr/bin/env bash
# modifies the Nginx configuration to change the listening port from 8080 to 80, restarts the Nginx service, and clears the Nginx PID file.
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
service nginx restart
echo "" > /run/nginx.pid
