#!/usr/bin/env bash
# Process and PID file

echo $$ > /var/run/myscript.pid

trem_del()
{
    rm /var/run/myscript.pid
    exit
}

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'echo "I hate the kill command" && trem_del' SIGTERM
    trap 'trem_del' SIGQUIT
done
