#!/usr/bin/env bash
# Init script to manage the manage_my_process script
# Provides start, stop, and restart functionality

i=0
while [ $i -eq 1 ]
do
    echo 'I am alive' >> /tmp/my_process
    sleep 2
done
