#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

num=0
while [ $num -lt 10 ]
do
    if [ $num -eq 8 ]
    then
	echo "Best School"
        echo "Hi"
    else
         echo "Best School"
    fi
    
    num=$(( num+1 ))
done
